build:
  script:
    - make all
  artifacts:
    paths:
      - manual/manual-de.pdf
      - manual/manual-en.pdf
      - template-de.tar.bz2
      - template-de.zip
      - template-en.tar.bz2
      - template-en.zip
